spring:
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
      connections.max.idle.ms: 540000
      request.timeout.ms: 30000
    consumer:
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
    producer:
      properties:
        max.block.ms: 30000
